#!/bin/bash

# cleanup
rm -rf "common/src/main/resources/data/rctmod/advancement"
rm -rf "common/src/main/resources/data/rctmod/dialog"
rm -rf "common/src/main/resources/data/rctmod/loot_table/trainers/groups"
rm -rf "common/src/main/resources/data/rctmod/loot_table/trainers/single"
rm -rf "common/src/main/resources/data/rctmod/mobs"
rm -rf "common/src/main/resources/data/rctmod/recipe"
rm -rf "common/src/main/resources/data/rctmod/series"
rm -rf "common/src/main/resources/data/rctmod/trainer_types"

# see https://gitlab.com/srcmc/rct/spreadsheets for more info
curl -s -S "https://gitlab.com/srcmc/rct/spreadsheets/-/raw/master/jcy.all.yaml" | jcy -out "common/src/main/resources"

rctltp -out "common/src/main/resources/data/rctmod/loot_table" \
  -sheet_url_items "https://gitlab.com/srcmc/rct/spreadsheets/-/raw/master/spreadsheet/loot_tables.csv" \
  -sheet_url_distributions "https://gitlab.com/srcmc/rct/spreadsheets/-/raw/master/spreadsheet/loot_table_distributions.csv" \
  -sheet_url_pools "https://gitlab.com/srcmc/rct/spreadsheets/-/raw/master/spreadsheet/loot_table_pools.csv" \
  -sheet_url_categories "https://gitlab.com/srcmc/rct/spreadsheets/-/raw/master/spreadsheet/loot_table_categories.csv" \
  -modIds "minecraft,cobblemon" \
  -poolIds "default,masterball" \
  -categoryIds "battle,berries,nature,fishing,medicine,pokeballs,training,evolution,archeology,diverse,masterball"

echo "assets generated"
