#!/bin/bash

## Dependencies
# - rcttrp installed - https://gitlab.com/srcmc/rct/rcttrp

## Config
RADICALRED_SOURCE=${RADICALRED_SOURCE:-"https://gitlab.com/srcmc/rct/rcttrp/-/raw/master/dumps/radical_red_3_02_trainers.txt?ref_type=heads"}
BDSP_SOURCE=${BDSP_SOURCE:-"https://gitlab.com/srcmc/rct/rcttrp/-/raw/master/dumps/bdsp_1_1.csv?ref_type=heads"}
UNBOUND_SOURCE=${UNBOUND_SOURCE:-"https://gitlab.com/srcmc/rct/rcttrp/-/raw/master/dumps/unbound_2_0_3_2_modified.txt?ref_type=heads"}
OUT="common/src/main/resources/data/rctmod/trainers"

## Commands
rm -rf "$OUT" && mkdir -p "$OUT"
rcttrp -out "$OUT" -parse-radicalred "$RADICALRED_SOURCE" -parse-bdsp "$BDSP_SOURCE" -parse-unbound "$UNBOUND_SOURCE"
echo "trainers generated"
