#!/bin/bash

## Dependencies
# - rcttrp installed - https://gitlab.com/srcmc/rct/rcttrp

## Config
RADICALRED_SOURCE=${RADICALRED_SOURCE:-"https://gitlab.com/srcmc/rct/rcttrp/-/raw/master/dumps/radical_red_3_02_trainers.txt"}
BDSP_SOURCE=${BDSP_SOURCE:-"https://docs.google.com/spreadsheets/d/1_uRpnFWroeCY3RaRi4lXeS9uZEDXiRIMBtTQVGrIZ3w/export?gid=773204596&format=csv"}
UNBOUND_SOURCE=${UNBOUND_SOURCE:-"https://pastebin.com/raw/dRj8YnX0"}
OUT="common/src/main/resources/data/rctmod/trainers"

## Commands
rm -rf "$OUT" && mkdir -p "$OUT"
rcttrp -out "$OUT" -parse-radicalred "$RADICALRED_SOURCE" -parse-bdsp "$BDSP_SOURCE" -parse-unbound "$UNBOUND_SOURCE"
echo "trainers generated"
