modLoader="javafml"
showAsResourcePack=false
loaderVersion="[${neoforge_loader_version},)"
license="${license}"

[[mods]]
  modId="${mod_id}"
  version="${mod_version}"
  displayName="${mod_name}"
  logoFile="assets/${mod_id}/icon.png"
  authors="${mod_author}"
  description='''${mod_description}'''

[[dependencies.${mod_id}]]
  modId="neoforge"
  mandatory=true
  versionRange="[${neoforge_major_version},)"
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
  modId="minecraft"
  mandatory=true
  versionRange="[${minecraft_version}]"
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
  modId="cobblemon"
  mandatory=true
  versionRange="[${cobblemon_min_ver},${cobblemon_max_ver})"
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
  modId="rctapi"
  mandatory=true
  versionRange="[${rctapi_version},)"
  ordering="NONE"
  side="BOTH"
