#!/bin/bash
# Simple script to generate some assets of the mod.

RES_PATH=common/src/main/resources
SECTORS="single groups"
CONTEXTS="textures"

for sector in $SECTORS; do
    for context in $CONTEXTS; do
        case $context in
            textures)
                suffix=.png ;;
            *)
                suffix=.json ;;
        esac

        case $sector in
            single)
                path="$RES_PATH/data/rctmod/trainers" ;;
            groups)
                path="$RES_PATH/data/rctmod/mobs/trainers/$sector" ;;
        esac

        find "$path" -name '*.json' | while read line; do
            id=$(basename $line)
            target_file="$RES_PATH/assets/rctmod/$context/trainers/$sector/${id%.json}$suffix"
            default_file="$RES_PATH/assets/rctmod/$context/trainers/default$suffix"

            if [ ! -f "$target_file" ]; then
                echo "creating '$target_file'"
                cp "$default_file" "$target_file"
            fi
        done
    done
done